networks:
  default:
    name: 'postcrossing_networks'
    
volumes:
  postcrossing_postgres:
    
services:
  postgres:
    image: 'postgres:latest'
    container_name: 'post_postgres'
    ports:
      - '5432:5432'
    volumes:
      - postcrossing_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 'admin'
      POSTGRES_USER: 'admin'
      POSTGRES_DB: 'postcrossing'